github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/xfantazy-downloader",
  "https://serp.co/products/xfantazy-downloader/reviews/",
  "https://extensions.serp.co/xfantazy-downloader",
  "https://browserextensions.io/xfantazy-downloader"
]
